import { clients as c, employees as e, serviceTypes as t, schedules as s } from './data.js';
const state={tab:'painel',query:'',status:'Todos',date:'',clients:[...c],employees:[...e],serviceTypes:[...t],schedules:[...s]};
const tabs=[['painel','📋','Painel'],['clientes','👥','Clientes'],['funcionarios','🧑‍🔧','Funcionários'],['tipos','🛠️','Tipos de serviços'],['programacao','📅','Programação']];
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v); const id=arr=>Math.max(0,...arr.map(i=>i.id))+1;
function filtered(){return state.schedules.filter(x=>JSON.stringify(x).toLowerCase().includes(state.query.toLowerCase())&&(state.status==='Todos'||x.status===state.status)&&(!state.date||x.data===state.date)).sort((a,b)=>`${a.data} ${a.horario}`.localeCompare(`${b.data} ${b.horario}`));}
function render(){document.querySelector('#app').innerHTML=`<aside class="sidebar"><div class="brand"><span>HV</span><div><strong>HaxVetor</strong><small>Dedetizadora</small></div></div><nav>${tabs.map(([key,ico,label])=>`<button data-tab="${key}" class="${state.tab===key?'active':''}">${ico} ${label}</button>`).join('')}</nav></aside><section class="content"><header><div><p>Sistema interno • dados fictícios</p><h1>${tabs.find(x=>x[0]===state.tab)[2]}</h1></div><button id="new-service" class="primary">＋ Novo serviço</button></header>${content()}</section>`; bind();}
function content(){if(state.tab==='painel')return `<div class="cards">${[['Clientes',state.clients.length],['Funcionários',state.employees.length],['Tipos de serviço',state.serviceTypes.length],['Serviços agendados',state.schedules.filter(x=>!['Concluído','Cancelado'].includes(x.status)).length]].map(x=>`<article class="card"><small>${x[0]}</small><strong>${x[1]}</strong></article>`).join('')}</div>${board(filtered().slice(0,4),false)}`; if(state.tab==='clientes')return table('clients','Clientes'); if(state.tab==='funcionarios')return table('employees','Funcionários'); if(state.tab==='tipos')return table('serviceTypes','Tipos de serviços'); return `<div class="filters"><label>🔎 Busca<input id="query" placeholder="Cliente, equipe, material..." value="${state.query}"></label><label>Status<select id="status">${['Todos','Agendado','Em atendimento','Concluído','Cancelado'].map(o=>`<option ${state.status===o?'selected':''}>${o}</option>`).join('')}</select></label><label>Data<input id="date" type="date" value="${state.date}"></label></div>${board(filtered(),true)}`;}
function table(key,title){const rows=state[key], keys=Object.keys(rows[0]).filter(k=>k!=='id');return `<section class="panel"><div class="panel-title"><h2>${title}</h2><button data-add="${key}" class="primary">＋ Criar</button></div><div class="table-wrap"><table><thead><tr>${keys.map(k=>`<th>${k}</th>`).join('')}<th>Ações</th></tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td><input data-edit="${key}" data-id="${r.id}" data-field="${k}" value="${r[k]}"></td>`).join('')}<td><button class="danger" data-del="${key}" data-id="${r.id}">🗑️</button></td></tr>`).join('')}</tbody></table></div></section>`}
function board(rows,actions){return `<section class="board">${rows.map(x=>`<article class="service"><div><strong>${x.horario} • ${x.cliente}</strong><span>${x.data} | ${x.status} | ${x.pagamento}</span></div><p>${x.tipoServico} em ${x.endereco}. Contato: ${x.contato}</p><p><b>Equipe:</b> ${x.equipe.join(', ')} • <b>Veículo:</b> ${x.veiculo}</p><p><b>Materiais:</b> ${x.materiais}</p><p><b>Obs.:</b> ${x.observacoes}</p><footer><b>${money(x.valor)}</b>${actions?`<button class="danger" data-del="schedules" data-id="${x.id}">🗑️ Excluir</button>`:''}</footer></article>`).join('')}</section>`}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});document.querySelector('#new-service').onclick=()=>{state.schedules.unshift({...state.schedules[0],id:id(state.schedules),data:new Date().toISOString().slice(0,10),horario:'10:00',status:'Agendado',pagamento:'Pendente',observacoes:'Novo registro fictício criado para edição.'});state.tab='programacao';render()};document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const k=b.dataset.add, base={clients:{nome:'Novo cliente fictício',endereco:'Endereço de exemplo',contato:'(11) 90000-0000',email:'novo@exemplo.com',tipo:'Residencial'},employees:{nome:'Novo funcionário fictício',cargo:'Técnico',telefone:'(11) 98888-0000',disponibilidade:'A definir'},serviceTypes:{nome:'Novo serviço',duracao:'1h',valorBase:100,descricao:'Descrição fictícia'}}[k];state[k].unshift({id:id(state[k]),...base});render()});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{state[b.dataset.del]=state[b.dataset.del].filter(x=>x.id!=b.dataset.id);render()});document.querySelectorAll('[data-edit]').forEach(i=>i.oninput=()=>{const row=state[i.dataset.edit].find(x=>x.id==i.dataset.id);row[i.dataset.field]=isNaN(Number(i.value))?i.value:Number(i.value)});['query','status','date'].forEach(k=>{const el=document.querySelector('#'+k); if(el)el.oninput=()=>{state[k]=el.value;render()}})}
render();
